package scanner;

public enum TokenType {
    IDENTIFICADOR,
    VAR, INTEIRO, REAL, TEXTO, SE, SENAO, PARA, IMPRIMIR, LER,
    LITERAL_INTEIRO, LITERAL_REAL, LITERAL_TEXTO,
    MAIS, MENOS, MULTIPLICACAO, DIVISAO,
    MENOR, MENOR_IGUAL, MAIOR, MAIOR_IGUAL,
    IGUAL_IGUAL, DIFERENTE,
    E_LOGICO, OU_LOGICO, NEGACAO,
    ATRIBUICAO,
    ABRE_PARENTESE, FECHA_PARENTESE,
    ABRE_CHAVE, FECHA_CHAVE,
    PONTO_VIRGULA, VIRGULA,
    EOF
}
